
# Frontend Ingress manifest - Used by frontend application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogger-webapp-ingress
spec:
  rules:
  - host: remotehomelab.be
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: blogger-webapp-service
            port:
              number: 80
